/**
 * Chinese names for the fields of each block, so a schema-derived form reads like
 * the reports it edits.
 *
 * The schema is the source of truth for *which* fields exist; this is
 * presentation only. `fieldLabel` falls back to the raw key, and a guard test
 * asserts that every field the schema declares for every block has a label here,
 * so a new schema field cannot silently show up as `someNewKey`.
 */

/** Labels that read well wherever the key appears. */
export const FIELD_LABELS: Readonly<Record<string, string>> = {
  after: "之后",
  align: "对齐",
  alt: "替代文字",
  badges: "徽章",
  before: "之前",
  blocking: "是否阻塞",
  body: "内容",
  caption: "说明",
  cells: "单元格",
  change: "变更类型",
  checked: "已完成",
  children: "子内容",
  chosen: "选定方案",
  code: "代码",
  columns: "列",
  complexity: "复杂度",
  context: "背景",
  date: "日期",
  defaultOpen: "默认展开",
  definition: "释义",
  delta: "变化",
  description: "说明",
  detail: "详情",
  diagramKind: "图类型",
  endpoints: "接口",
  events: "事件",
  failed: "失败数",
  filename: "文件名",
  goals: "目标",
  href: "链接地址",
  importance: "重要度",
  items: "条目",
  key: "键名",
  label: "名称",
  language: "语言",
  layout: "布局",
  lead: "导语",
  level: "级别",
  likelihood: "可能性",
  links: "链接",
  locator: "定位",
  method: "方法",
  metrics: "指标",
  mitigation: "应对措施",
  modules: "模块",
  name: "名称",
  nonNegotiable: "是否不可协商",
  note: "说明",
  notes: "备注",
  options: "备选方案",
  overview: "架构总览",
  panels: "页签",
  passed: "通过数",
  path: "路径",
  phases: "阶段",
  progress: "进度",
  question: "问题",
  rationale: "理由",
  reqId: "需求编号",
  root: "文件树",
  rows: "行",
  rule: "约束规则",
  scope: "范围",
  severity: "严重程度",
  skipped: "跳过数",
  source: "图源码 / 来源",
  src: "图片地址",
  statement: "假设陈述",
  status: "状态",
  steps: "步骤",
  suites: "测试套件",
  summary: "折叠标题",
  tags: "标签",
  term: "术语",
  terms: "术语表",
  text: "正文",
  timeframe: "时间范围",
  title: "标题",
  tone: "基调",
  unified: "统一 diff",
  unit: "单位",
  url: "链接地址",
  validated: "是否已验证",
  value: "值",
  variant: "样式",
  visible: "是否对读者可见",
  width: "宽度",
};

/**
 * Per-block overrides, for the places where the same key means something else —
 * a `text` is "写一段话" in a paragraph but "引用内容" in a blockquote.
 * Taken from the labels the previous editor showed.
 */
export const BLOCK_FIELD_LABELS: Readonly<
  Record<string, Readonly<Record<string, string>>>
> = {
  appendix: { children: "附录正文", title: "附录标题" },
  architectureOverview: {
    modules: "模块列表",
    overview: "架构总览内容",
  },
  agentNote: { text: "备注内容", visible: "是否对读者可见" },
  blockquote: { text: "引用内容" },
  callout: { body: "提示内容", title: "小标题（可选）", variant: "提示类型" },
  checklist: { items: "清单条目" },
  citation: { items: "出处" },
  code: {
    code: "代码内容",
    filename: "文件名（可选）",
    language: "语言（可选）",
  },
  codeDiff: {
    after: "修改后",
    before: "修改前",
    filename: "文件名（可选）",
    language: "语言（可选）",
  },
  collection: {
    items: "信息卡片",
    title: "标题（可选）",
    variant: "展示样式",
  },
  collapsible: {
    children: "折叠内容",
    defaultOpen: "默认展开",
    summary: "折叠标题",
  },
  comparison: {
    after: "之后",
    before: "之前",
    labelAfter: "右侧标题（可选）",
    labelBefore: "左侧标题（可选）",
  },
  constraint: {
    nonNegotiable: "是否不可协商",
    rule: "约束规则",
    scope: "适用范围（可选）",
  },
  decision: {
    chosen: "选定方案（可选）",
    context: "背景（可选）",
    options: "备选方案（可选）",
    rationale: "决策理由（可选）",
    status: "当前状态",
    title: "决策标题",
  },
  definitionList: { items: "名词与释义" },
  embed: { title: "标题（可选）", url: "链接地址" },
  fileChangeList: { items: "变更文件" },
  fileTree: { caption: "说明（可选）", root: "文件树（纯文本）" },
  flowSteps: { steps: "步骤" },
  glossary: { terms: "术语表" },
  group: { children: "分组正文", title: "分组名称（可选）" },
  heading: { level: "标题级别", text: "标题文字" },
  hero: { metrics: "顶部指标" },
  image: { alt: "替代文字", caption: "图注（可选）", src: "图片地址" },
  keyValueList: { items: "键值对", layout: "布局" },
  lead: { text: "导语内容" },
  linkList: { links: "链接列表", title: "标题（可选）" },
  mermaid: {
    complexity: "复杂度（可选）",
    diagramKind: "图类型",
    source: "图内容",
    title: "标题（可选）",
  },
  openQuestion: { blocking: "是否阻塞", question: "待确认问题" },
  paragraph: { text: "写一段话" },
  pullQuote: { text: "要强调的句子" },
  requirementTrace: { items: "需求追溯" },
  risk: {
    description: "风险说明",
    likelihood: "可能性（可选）",
    mitigation: "应对措施（可选）",
    severity: "严重程度",
    status: "状态",
    title: "风险标题",
  },
  roadmap: { goals: "目标（可选）", phases: "阶段" },
  section: {
    children: "章节正文",
    lead: "导语（可选）",
    title: "章节名称",
  },
  spacer: { size: "空白大小" },
  statusBoard: { items: "状态卡片" },
  table: { columns: "列", rows: "行" },
  testResult: { suites: "测试套件" },
  timeline: { events: "时间节点" },
};

/** What to show as a field's name: the block's own label, else the shared one. */
export function fieldLabel(blockType: string, key: string): string {
  return BLOCK_FIELD_LABELS[blockType]?.[key] ?? FIELD_LABELS[key] ?? key;
}
